version: "{build}"

build:
  verbosity: normal

clone_folder: "c:\\WORK"
clone_depth: 5

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

platform:
  - x86_64

deploy: off

cache:
  - "C:\\SR"
  - dist-newstyle

environment:
  global:
    CABOPTS: --store-dir=C:\\SR

  matrix:
    - GHCVER: 8.8.3

# enable RDP, see https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
  - choco install -y cabal --version 3.0.0.0
  - choco install -y ghc   --version %GHCVER%
  - choco install -y r
  - refreshenv

before_build:
  - cabal --version
  - ghc   --version
  - cabal %CABOPTS% update

build_script:
  - cabal %CABOPTS% build all --extra-lib-dirs="C:/Program files/R/R-3.6.3/bin/x64" --extra-include-dirs="C:/Program files/R/R-3.6.3/include"
