resolver: lts-12.20

packages:
- examples
- H
- IHaskell
- inline-r

extra-deps:
- ihaskell-0.9.1.0
- ihaskell-blaze-0.3.0.1

docker:
  # Disabled by default. Use --docker on command line to enable.
  enable: false
  repo: tweag/haskellr:latest

nix:
  shell-file: ./shell.nix
  path: ["nixpkgs=./nixpkgs.nix"]
